#include "books.hpp"

bookmark book_list[] =
{
    BOOK(Genesis, Gen),
    BOOK(Exodus, Exod),
    BOOK(Leviticus, Lev),
    BOOK(Numbers, Num),
    BOOK(Deuteronomy, Deut),
    BOOK(Joshua, Josh),
    BOOK(Judges, Judg),
    BOOK(Ruth, Ruth),
    BOOK(1 Samuel, 1Sam),
    BOOK(2 Samuel, 2Sam),
    BOOK(1 Kings, 1Kgs),
    BOOK(2 Kings, 2Kgs),
    BOOK(1 Chronicles, 1Chr),
    BOOK(2 Chronicles, 2Chr),
    BOOK(Ezra, Ezra),
    BOOK(Nehemiah, Neh),
    BOOK(Esther, Esth),
    BOOK(Job, Job),
    BOOK(Psalm, Ps),
    BOOK(Proverbs, Prov),
    BOOK(Ecclesiastes, Eccl),
    BOOK(Song of Solomon, Song),
    BOOK(Isaiah, Isa),
    BOOK(Jeremiah, Jer),
    BOOK(Lamentations, Lam),
    BOOK(Ezekiel, Ezek),
    BOOK(Daniel, Dan),
    BOOK(Hosea, Hos),
    BOOK(Joel, Joel),
    BOOK(Amos, Amos),
    BOOK(Obadiah, Obad),
    BOOK(Jonah, Jonah),
    BOOK(Micah, Mic),
    BOOK(Nahum, Nah),
    BOOK(Habakkuk, Hab),
    BOOK(Zephaniah, Zeph),
    BOOK(Haggai, Hag),
    BOOK(Zechariah, Zech),
    BOOK(Malachi, Mal),
    BOOK(Matthew, Matt),
    BOOK(Mark, Mark),
    BOOK(Luke, Luke),
    BOOK(John, John),
    BOOK(Acts, Acts),
    BOOK(Romans, Rom),
    BOOK(1 Corinthians, 1Cor),
    BOOK(2 Corinthians, 2Cor),
    BOOK(Galatians, Gal),
    BOOK(Ephesians, Eph),
    BOOK(Philippians, Phil),
    BOOK(Colossians, Col),
    BOOK(1 Thessalonians, 1Thess),
    BOOK(2 Thessalonians, 2Thess),
    BOOK(1 Timothy, 1Tim),
    BOOK(2 Timothy, 2Tim),
    BOOK(Titus, Titus),
    BOOK(Philemon, Phlm),
    BOOK(Hebrews, Heb),
    BOOK(James, Jas),
    BOOK(1 Peter, 1Pet),
    BOOK(2 Peter, 2Pet),
    BOOK(1 John, 1John),
    BOOK(2 John, 2John),
    BOOK(3 John, 3John),
    BOOK(Jude, Jude),
    BOOK(Revelation, Rev)
};
