#include "books.hpp"

bookmark book_list[] =
{
    BOOK(Genesis, Gen, genesis),
    BOOK(Exodus, Exod, exodus),
    BOOK(Leviticus, Lev, leviticus),
    BOOK(Numbers, Num, numbers),
    BOOK(Deuteronomy, Deut, deuteronomy),
    BOOK(Joshua, Josh, joshua),
    BOOK(Judges, Judg, judges),
    BOOK(Ruth, Ruth, ruth),
    BOOK(1 Samuel, 1Sam, 1-samuel),
    BOOK(2 Samuel, 2Sam, 2-samuel),
    BOOK(1 Kings, 1Kgs, 1-kings),
    BOOK(2 Kings, 2Kgs, 2-kings),
    BOOK(1 Chronicles, 1Chr, 1-chronicles),
    BOOK(2 Chronicles, 2Chr, 2-chronicles),
    BOOK(Ezra, Ezra, ezra),
    BOOK(Nehemiah, Neh, nehemiah),
    BOOK(Esther, Esth, esther),
    BOOK(Job, Job, job),
    BOOK(Psalm, Ps, psalms),
    BOOK(Proverbs, Prov, proverbs),
    BOOK(Ecclesiastes, Eccl, ecclesiastes),
    BOOK(Song of Solomon, Song, song-of-solomon),
    BOOK(Isaiah, Isa, isaiah),
    BOOK(Jeremiah, Jer, jeremiah),
    BOOK(Lamentations, Lam, lamentations),
    BOOK(Ezekiel, Ezek, ezekiel),
    BOOK(Daniel, Dan, daniel),
    BOOK(Hosea, Hos, hosea),
    BOOK(Joel, Joel, joel),
    BOOK(Amos, Amos, amos),
    BOOK(Obadiah, Obad, obadiah),
    BOOK(Jonah, Jonah, jonah),
    BOOK(Micah, Mic, micah),
    BOOK(Nahum, Nah, nahum),
    BOOK(Habakkuk, Hab, habakkuk),
    BOOK(Zephaniah, Zeph, zephaniah),
    BOOK(Haggai, Hag, haggai),
    BOOK(Zechariah, Zech, zechariah),
    BOOK(Malachi, Mal, malachi),
    BOOK(Matthew, Matt, matthew),
    BOOK(Mark, Mark, mark),
    BOOK(Luke, Luke, luke),
    BOOK(John, John, john),
    BOOK(Acts, Acts, acts),
    BOOK(Romans, Rom, romans),
    BOOK(1 Corinthians, 1Cor, 1-corinthians),
    BOOK(2 Corinthians, 2Cor, 2-corinthians),
    BOOK(Galatians, Gal, galatians),
    BOOK(Ephesians, Eph, ephesians),
    BOOK(Philippians, Phil, philippians),
    BOOK(Colossians, Col, colossians),
    BOOK(1 Thessalonians, 1Thess, 1-thessalonians),
    BOOK(2 Thessalonians, 2Thess, 2-thessalonians),
    BOOK(1 Timothy, 1Tim, 1-timothy),
    BOOK(2 Timothy, 2Tim, 2-timothy),
    BOOK(Titus, Titus, titus),
    BOOK(Philemon, Phlm, philemon),
    BOOK(Hebrews, Heb, hebrews),
    BOOK(James, Jas, james),
    BOOK(1 Peter, 1Pet, 1-peter),
    BOOK(2 Peter, 2Pet, 2-peter),
    BOOK(1 John, 1John, 1-john),
    BOOK(2 John, 2John, 2-john),
    BOOK(3 John, 3John, 3-john),
    BOOK(Jude, Jude, jude),
    BOOK(Revelation, Rev, revelation)
};
